### ISSUE TITLE
No validator_balance from metrics

### ISSUE THREAD

**Issue by hoangong** [GuillaumeMiralles/prysm-grafana-dashboard#1]
Hi,

The issue is that: I imported the dashboard successfully but It could not found `validator_balance` metric from some of the panels. According to this prometheus has only `validators_total_balance`. This prometheus links to both beacon and validator nodes.
<img width="702" alt="Screenshot 2020-05-09 at 22 12 48" src="https://user-images.githubusercontent.com/5703525/81485133-c511db00-9242-11ea-902f-5417fd652763.png">

I already pull the latest prysm's client. Do you have any idea of the issue?

Thanks.

**Comment by GuillaumeMiralles** [comment]
I think that you don't get the validator client metrics, but only the beacon-node metrics.

You probably forgot to add the flag `--enable-account-metrics` on your validator command. By default the validator doesn't return any metrics, and you have to enable that with this flag.

**Comment by hoangong** [comment]
I can see the metrics now. thank you
