### ISSUE TITLE
No value for total_voted_target_balances on mainnet?

### ISSUE THREAD

**Issue by erik78se** [GuillaumeMiralles/prysm-grafana-dashboard#15]
I'm following this guide: https://docs.prylabs.network/docs/prysm-usage/monitoring/grafana-dashboard

I'm not sure if I'm doing something wrong, or if there is an issue with the dashboard. or the fact that as of time of writing this -  the mainnet is not yet running.

My problem is that I can't get the key for **total_voted_target_balances** which seems to be important.

I can find "validator_statuses", but the "total_voted_target_balances" is not there at all. No key nor value.

**Comment by GuillaumeMiralles** [comment]
This key isn't foundable until the mainnet will start, and this is also true for others metric that aren't available right now until the mainnet will start.

Some context for this metric: it represents the quantity of validator that participated for the vote, which is very useful to calculate the participation rate. If this participation rate goes below than 66%, then the network cannot finalized block, and even if you are running your validators properly, you won't be able to get any reward until this participation rate goes above 66% again.

**Comment by erik78se** [comment]
Thanx alot for the exmplanation. I'm running your stuff now and it looks and works great!
