### ISSUE TITLE
Docker (Kubernetes) fails to get Node Process Started and Process down alerts

### ISSUE THREAD

**Issue by steflsd** [GuillaumeMiralles/prysm-grafana-dashboard#17]
As seen in the screenshot, im running the exporter on a Kubernetes pod and it fails to get the following alerts

![image](https://user-images.githubusercontent.com/2960424/100697012-8d64af00-339d-11eb-949e-4c8c4f517e1d.png)

**Comment by GuillaumeMiralles** [comment]
Hi!

Could you please paste the content of your prometheus.yml file here, I need to make sure about something

**Comment by steflsd** [comment]
Hi

<pre>
prometheus:
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false

  server:
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    retention: "31d"

    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      mountPath: /data

  serverFiles:
    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanager:9093
    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    prometheus.yml:
      rule_files:
        # - "first_rules.yml"
        # - "second_rules.yml"
      # A scrape configuration containing exactly one endpoint to scrape:
      # Here it's Prometheus itself.
      scrape_configs:
        - job_name: 'validator'
          static_configs:
            - targets: ['prysm-validator:8081']
        - job_name: 'beacon'
          static_configs:
            - targets: ['prysm-beacon:8080']
        - job_name: 'slasher'
          static_configs:
            - targets: ['prysm-slasher:8082']
</pre>

**Comment by GuillaumeMiralles** [comment]
Your issue is coming from here, you should replace the job_name `beacon` by `beacon node`
```
        - job_name: 'beacon node'
          static_configs:
            - targets: ['prysm-beacon:8080']
```

**Comment by steflsd** [comment]
Thanks very much. Issue is resolved.
