### ISSUE TITLE
Link to "To have access to the currency converter, you can find how" broken

### ISSUE THREAD

**Issue by chrishobcroft** [GuillaumeMiralles/prysm-grafana-dashboard#4]
![image](https://user-images.githubusercontent.com/2212651/84247262-77301180-ab25-11ea-8fe7-a0b2707e7711.png)

Tries to open this page: https://docs.prylabs.network/docs/prysm-usage/monitoring/currency_converter/

![image](https://user-images.githubusercontent.com/2212651/84247327-92028600-ab25-11ea-882d-3afc929aebe4.png)

But keep up the great work!

**Comment by GuillaumeMiralles** [comment]
Yeah I anticipated the prysm guide, but it takes a bit too much time to get approved.
Instead you can use the guide from this repo here https://github.com/GuillaumeMiralles/prysm-grafana-dashboard/blob/master/currency_converter.md
