### ISSUE TITLE
Total earning panel is not working

### ISSUE THREAD

**Issue by GuillaumeMiralles** [GuillaumeMiralles/prysm-grafana-dashboard#5]
That's a known issue that exist since genesis of Onyx testnet, this is not from my end, I created a git issue on prysm repository so they could fix this. https://github.com/prysmaticlabs/prysm/issues/6241

Sorry in advance!

**Comment by prestonvanloon** [comment]
prysmaticlabs/prysm#6241 has been resolved and will be included in the next release. (ETA: in the next 2 days)
