### ISSUE TITLE
Parse error(s) in >10 validators json

### ISSUE THREAD

**Issue by danielschonfeld** [GuillaumeMiralles/prysm-grafana-dashboard#6]
In the CPU graphing:
```parse error at char 60: unexpected metric identifier \":5s\" in range selector, expected \"]\""```

Earnings data:
```"parse error at char 184: range specification must be preceded by a metric selector, but follows a *promql.AggregateExpr instead"```

**Comment by GuillaumeMiralles** [comment]
Investigating now

**Comment by GuillaumeMiralles** [comment]
I just imported the `more 10 validators` dashboard, and nothing wrong on my own.

I suggest you to try to re import the dashboard, if you keep facing issues, then contact me directly on discord (Ocaa/grums) that will be easier/faster

**Comment by danielschonfeld** [comment]
texting you on discord now

**Comment by GuillaumeMiralles** [comment]
@danielschonfeld was using prometheus version 2.1.0

To resolve this issue, it was required to upgrade prometheus more recent version
